Repository ibexa/post-install, pull requests merged in 2024-07, with the labels that each got.

#79 Bump PHP version in p.sh configuration for 1.0 branch (DXP 3.3)
  resources/platformsh/ibexa-commerce/3.3/.platform.app.yaml
  resources/platformsh/ibexa-content/3.3/.platform.app.yaml
  resources/platformsh/ibexa-experience/3.3/.platform.app.yaml
  resources/platformsh/ibexa-oss/3.3/.platform.app.yaml
Labels: Improvement, Ready for review

#71 IBX-7806: Added missing random fields in solr schema
  resources/platformsh/ibexa-commerce/3.3/.platform/configsets/solr6/conf/schema.xml
Labels: QA approved, Ready for review

#72 IBX-7806: Added missing random fields in solr schema
  resources/platformsh/ibexa-commerce/4.6/.platform/configsets/solr6/conf/schema.xml
Labels: QA approved, Ready for review

#78 IBX-8506: Disabled display_errors in Cloud
  resources/platformsh/ibexa-commerce/3.3/.platform.app.yaml
  resources/platformsh/ibexa-content/3.3/.platform.app.yaml
  resources/platformsh/ibexa-experience/3.3/.platform.app.yaml
  resources/platformsh/ibexa-oss/3.3/.platform.app.yaml
Labels: Ready for QA, Doc needed
